"""initial migration

Revision ID: d55fb3bce6d2
Revises: 3c5f9b6838fc
Create Date: 2025-12-31 13:47:48.876655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd55fb3bce6d2'
down_revision = '3c5f9b6838fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_configurations_team_id'), table_name='alert_configurations')
    op.drop_index(op.f('ix_alert_configurations_tenant_id'), table_name='alert_configurations')
    op.drop_index(op.f('ix_alert_configurations_tenant_team'), table_name='alert_configurations')
    op.drop_table('alert_configurations')
    op.drop_index(op.f('ix_alert_escalations_alert_id'), table_name='alert_escalations')
    op.drop_index(op.f('ix_alert_escalations_escalated_at'), table_name='alert_escalations')
    op.drop_table('alert_escalations')
    op.drop_index(op.f('ix_alerts_booking_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_employee_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tenant_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_tenant_status'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_triggered_at'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_alert_notifications_alert_id'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_channel'), table_name='alert_notifications')
    op.drop_index(op.f('ix_alert_notifications_status'), table_name='alert_notifications')
    op.drop_table('alert_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_notifications',
    sa.Column('notification_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('recipient_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('recipient_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('recipient_role', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('channel', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('delivered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('failure_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name=op.f('alert_notifications_alert_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('alert_notifications_pkey'))
    )
    op.create_index(op.f('ix_alert_notifications_status'), 'alert_notifications', ['status'], unique=False)
    op.create_index(op.f('ix_alert_notifications_channel'), 'alert_notifications', ['channel'], unique=False)
    op.create_index(op.f('ix_alert_notifications_alert_id'), 'alert_notifications', ['alert_id'], unique=False)
    op.create_table('alerts',
    sa.Column('alert_id', sa.INTEGER(), server_default=sa.text("nextval('alerts_alert_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('booking_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('alert_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('severity', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('trigger_latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trigger_longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('trigger_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('evidence_urls', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('triggered_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('acknowledged_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('acknowledged_by_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('acknowledgment_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('estimated_arrival_minutes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('response_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('closed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('closed_by_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('resolution_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('resolution_time_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_false_alarm', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('auto_escalated', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.booking_id'], name='alerts_booking_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='alerts_employee_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('alert_id', name='alerts_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_alerts_triggered_at'), 'alerts', ['triggered_at'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_status'), 'alerts', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_alerts_tenant_id'), 'alerts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alerts_status'), 'alerts', ['status'], unique=False)
    op.create_index(op.f('ix_alerts_employee_id'), 'alerts', ['employee_id'], unique=False)
    op.create_index(op.f('ix_alerts_booking_id'), 'alerts', ['booking_id'], unique=False)
    op.create_table('alert_escalations',
    sa.Column('escalation_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('escalation_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('escalated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('escalated_to_recipients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('escalation_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_automatic', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.alert_id'], name=op.f('alert_escalations_alert_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('escalation_id', name=op.f('alert_escalations_pkey'))
    )
    op.create_index(op.f('ix_alert_escalations_escalated_at'), 'alert_escalations', ['escalated_at'], unique=False)
    op.create_index(op.f('ix_alert_escalations_alert_id'), 'alert_escalations', ['alert_id'], unique=False)
    op.create_table('alert_configurations',
    sa.Column('config_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('primary_recipients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('escalation_recipients', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('notification_channels', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('emergency_contacts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_escalation', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('notify_on_status_change', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('config_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('applicable_alert_types', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('enable_escalation', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('escalation_threshold_seconds', sa.INTEGER(), server_default=sa.text('300'), autoincrement=False, nullable=False),
    sa.Column('auto_close_false_alarm_seconds', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('require_closure_notes', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('enable_geofencing_alerts', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('geofence_radius_meters', sa.INTEGER(), server_default=sa.text('1000'), autoincrement=False, nullable=True),
    sa.Column('priority', sa.INTEGER(), server_default=sa.text('100'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['team_id'], ['teams.team_id'], name=op.f('alert_configurations_team_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id', name=op.f('alert_configurations_pkey'))
    )
    op.create_index(op.f('ix_alert_configurations_tenant_team'), 'alert_configurations', ['tenant_id', 'team_id'], unique=True)
    op.create_index(op.f('ix_alert_configurations_tenant_id'), 'alert_configurations', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alert_configurations_team_id'), 'alert_configurations', ['team_id'], unique=False)
    # ### end Alembic commands ###
