"""initial database schema

Revision ID: b75d731987dd
Revises: 
Create Date: 2025-12-18 18:46:56.258329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b75d731987dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Tables already exist in database, this migration marks the initial state
    # Adding named unique constraints for better management
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # This is the initial migration, downgrade does nothing
    pass
    # ### end Alembic commands ###
